#!/bin/bash

VOICE="cs-CZ-VlastaNeural"
RATE="-5%"
mkdir -p wav ogg

declare -A PHRASES
PHRASES=(
  [0]="Spouštím."
  [1]="Čekám na konfiguraci sítě."
  [2]="Nelze se připojit k Wi-Fi síti. Zkontrolujte heslo a zkuste to znovu."
  [3]="Nelze se připojit k serveru. Zkontrolujte místní síť a zkuste to znovu."
  [4]="Kougí ukončil režim konfigurace sítě."
  [5]="Síť úspěšně připojena."
  [6]="Připojení k síti selhalo. Zkuste to znovu později."
  [7]="Zahajuji úklid."
  [8]="Zahajuji bodový úklid."
  [9]="Zahajuji naplánovaný úklid."
  [10]="Pokračuji v úklidu."
  [11]="Pozastaveno."
  [12]="Úklid dokončen."
  [13]="Vracím se do základny k nabíjení."
  [14]="Nízký stav baterie. Vracím se do základny. Po nabití budu pokračovat."
  [15]="Vracím se na výchozí místo."
  [16]="Nízký stav baterie. Vracím se na výchozí místo. Prosím nabijte mě."
  [17]="Přesuňte Kougí do základny k nabíjení."
  [18]="Nabíjím."
  [19]="Před vypnutím přesuňte Kougí ze základny."
  [20]="Nízký stav baterie."
  [21]="Nízký stav baterie. Kougí se vypne."
  [22]="Přesuňte Kougí do oblasti, která má být vysávána."
  [23]="Nádrž na vodu byla nainstalována."
  [24]="Zkontrolujte, zda je nádrž na vodu správně nainstalována."
  [25]="Nízký stav baterie. Naplánovaný úklid nelze provést."
  [26]="Obnovuji tovární nastavení."
  [27]="Aktualizuji. Trvá přibližně pět minut. Nevypínejte Kougí ani nezahajujte úklid."
  [28]="Aktualizace úspěšně dokončena."
  [29]="Aktualizace selhala. Zkuste to znovu později."
  [30]="Určuji polohu, čekejte prosím."
  [31]="Určení polohy selhalo. Mapa je neplatná. Kougí zahájí nový úklid."
  [32]="Zjistil jsem změny prostředí. Stiskněte tlačítko a zahajte nový cyklus úklidu."
  [33]="Chyba vizuálního navigačního senzoru. Otřete jej a restartujte."
  [34]="Zásobník na prach není nainstalován. Nainstalujte jej."
  [35]="Chyba hlavního kartáče. Zkontrolujte a vyčistěte jej."
  [36]="Chyba bočního kartáče. Zkontrolujte a vyčistěte jej."
  [37]="Chyba pravého kola. Zkontrolujte a vyčistěte jej."
  [38]="Chyba levého kola. Zkontrolujte a vyčistěte jej."
  [39]="Vyčistěte senzor srážky s překážkou."
  [40]="Kougí uvízl. Přesuňte jej na nové místo a restartujte."
  [41]="Kola Kougía jsou ve vzduchu. Přesuňte Kougí zpět na zem."
  [42]="Zkontrolujte a vyčistěte filtr."
  [43]="Chyba nárazníku. Zkuste jej jemně stisknout, zda se odráží."
  [44]="Chyba. Zkontrolujte uživatelskou příručku nebo kontaktujte zákaznickou podporu."
  [45]="Jsem tady."
  [46]="Kougí a telefon jsou propojeny. Vraťte se do aplikace a čekejte na výsledek."
  [47]="Zahajuji nabíjení."
  [48]="Nízký stav baterie. Vracím se do základny."
  [49]="Zjištěno silné magnetické pole. Přesuňte Kougí a restartujte."
  [50]="Chyba nabíjení. Vyčistěte nabíjecí kontakty."
  [51]="Baterie se přehřívá nebo je příliš studená. Počkejte, až teplota baterie dosáhne normálních hodnot."
  [52]="Kougí je nakloněn. Umístěte jej na rovnou plochu a restartujte."
  [53]="Zjištěna virtuální zakázaná zóna. Přesuňte Kougí a restartujte."
  [54]="Poloha určena. Pokračuji v úklidu."
  [55]="Poloha určena. Pokračuji v návratu do základny."
  [56]="Zahajuji úklid vybraných místností."
  [57]="Zahajuji zónový úklid."
  [58]="Pokračuji v úklidové úloze."
  [59]="Mopování dokončeno. Včas odstraňte nádrž na vodu."
  [60]="Chyba optického senzoru toku. Otřete jej a restartujte."
  [61]="Zahajuji mopování."
  [62]="Zahajuji dálkově ovládaný úklid."
  [63]="Nádrž na vodu byla odebrána."
  [64]="Určení polohy selhalo. Mapa je neplatná. Kougí se vrátí do základny."
  [65]="Pokračuji v návratu do základny."
  [66]="Filtr je opotřebený. Včas jej vyměňte."
  [67]="Boční kartáč je opotřebený. Včas jej vyměňte."
  [68]="Hlavní kartáč je opotřebený. Včas jej vyměňte."
  [69]="Cesta úklidu je zablokována. Přesuňte Kougí na nové místo a restartujte."
  [70]="Odstraňte a vyčistěte mopovací podložku."
  [71]="Chyba laserového senzoru. Zkontrolujte a vyčistěte laserový senzor."
  [72]="Zkontrolujte, zda kryt laserového senzoru vzdálenosti není zablokován."
  [73]="Chyba hranového senzoru. Zkontrolujte a vyčistěte jej."
  [74]="Zkuste vyčistit senzory detekce překážek."
  [75]="Filtr nemusí být suchý nebo může být zablokován."
  [76]="Zahajuji bodový úklid."
  [77]="Spusťte Kougí mimo koberec."
  [78]="Vyčistěte 3D senzor vyhýbání se překážkám."
  [79]="Chyba 3D senzoru. Restartujte Kougí nebo kontaktujte zákaznickou podporu."
  [80]="Vysílač 3D senzoru nefunguje správně. Restartujte Kougí nebo kontaktujte zákaznický servis."
  [81]="Chyba ultrazvukového senzoru. Restartujte Kougí nebo kontaktujte zákaznickou podporu."
  [82]="Zahajuji mapování."
  [83]="Pokračuji v mapování."
  [84]="Mapování dokončeno."
  [85]="Poloha určena. Pokračuji v mapování."
  [86]="Určení polohy selhalo. Restartuji mapování."
  [87]="Nízký stav baterie. Vracím se do základny."
  [88]="Vstupuji do režimu dálkového ovládání."
  [89]="Pokračuji v nabíjení."
  [90]="Pokračuji v úklidové úloze."
  [91]="Nádrž na čistou vodu není nainstalována. Nainstalujte ji před pokračováním."
  [92]="Nádrž na špinavou vodu není nainstalována. Nainstalujte ji před pokračováním."
  [93]="V nádrži na čistou vodu není dostatek vody. Doplňte vodu před pokračováním."
  [94]="Nádrž na špinavou vodu je plná. Vylijte špinavou vodu před pokračováním."
  [95]="Podložka na mytí mopů není nainstalována. Kougí se nemůže vrátit do základny."
  [96]="Podložka na mytí mopů přetéká. Zkontrolujte, zda není zablokován odtok."
  [97]="Sáček na prach není nainstalován. Nainstalujte jej před pokračováním."
  [98]="Sáček na prach je plný. Vyměňte jej."
  [99]="Horní kryt základny není zavřený. Zavřete jej před pokračováním."
  [100]="Vzduchový kanál základny je zablokován. Zkontrolujte jej."
  [101]="Horní kryt základny není zavřený nebo sáček na prach není nainstalován. Zavřete kryt nebo nainstalujte sáček."
  [102]="Sáček na prach je plný nebo je vzduchový kanál zablokován. Vyměňte sáček nebo vyčistěte kanál."
  [103]="Podložka na mytí mopů je nainstalována. Kougí pokračuje v práci."
  [104]="Podložka na mytí mopů není nainstalována. Ujistěte se, že je správně nainstalována a svorky jsou pevně zajištěny."
  [105]="Zahajuji úklid."
  [106]="Zahajuji čištění mopu."
  [107]="Zahajuji odvodňování mopu."
  [108]="Hladina vody v podložce na mytí mopů je abnormální. Vyčistěte ji včas, aby nedošlo k ucpání."
  [109]="Došlo k výjimce v nádrži na špinavou vodu. Ujistěte se, že je nádrž nainstalována, a včas ji vyprázdněte."
  [110]="Zahajuji automatické vysypání."
  [111]="Mopovací podložky nejsou nasazeny. Nasaďte je před pokračováním."
  [112]="Umístěte Kougí zpět na základnu před použitím."
  [113]="Úloha dokončena. Včas vyprázdněte nádrž na odpad."
  [114]="Mopovací podložky nasazeny."
  [115]="Mopovací podložky odstraněny."
  [116]="Dětský zámek zapnut. Tlačítka jsou uzamčena."
  [117]="Dětský zámek vypnut. Tlačítka jsou odemčena."
  [118]="Tlačítka uzamčena. Přidržte tlačítko základny pro odemčení."
  [119]="Tlačítka uzamčena."
  [120]="Tlačítka odemčena."
  [121]="Kougí a telefon jsou propojeny. Vraťte se do aplikace a čekejte na dokončení připojení."
  [122]="Průběžné určování polohy, čekejte prosím."
  [126]="Zahajuji úklid."
  [127]="Zahajuji bodový úklid."
  [128]="Zahajuji bodové mopování."
  [129]="Zahajuji naplánovaný úklid."
  [130]="Zahajuji naplánované mopování."
  [131]="Zahajuji bodový úklid."
  [132]="Zahajuji bodové mopování."
  [133]="Zahajuji úklid vybraných místností."
  [134]="Zahajuji mopování vybraných místností."
  [135]="Zahajuji zónový úklid."
  [136]="Zahajuji zónové mopování."
  [137]="Pokračuji v úklidu."
  [138]="Pokračuji v mopování."
  [139]="Pokračuji v návratu do základny k čištění."
  [140]="Zjištěno nové prostředí. Vracím se do základny."
  [141]="Chyba mopovací podložky. Zkontrolujte a vyčistěte ji."
  [142]="Mopovací podložka je opotřebená. Včas ji vyměňte."
  [143]="Úklid dokončen."
  [144]="Mopování dokončeno."
  [145]="Poloha určena. Pokračuji v úklidu."
  [146]="Poloha určena. Pokračuji v mopování."
  [148]="Vracím se do základny k čištění."
  [149]="Nelze dosáhnout určené oblasti. Zkuste odstranit překážky na cestě."
  [150]="Nelze dosáhnout určené oblasti. Zkuste smazat zakázané zóny na cestě."
  [151]="Cesta je zablokována. Zkuste odstranit překážky kolem Kougía."
  [152]="Cesta je zablokována. Zkuste smazat zakázané zóny nebo přesuňte Kougí."
  [153]="Kougí byl zjištěn v zakázané zóně. Přesuňte Kougí z této oblasti."
  [154]="Příliš časté operace. Zkuste to znovu později."
  [155]="Vracím se do nabíjecí základny s čištěním mopů."
  [156]="Zásobník mopovací podložky odstraněn."
  [157]="Jsem již v nabíjecí základně s čištěním mopů."
  [200]="Vypínám."
)

echo "Generating Czech voice files..."

for key in "${!PHRASES[@]}"; do
  text="${PHRASES[$key]}"
  echo "[$key] $text"
  edge-tts --voice "$VOICE" --text "$text" --write-media "wav/${key}.wav"
done

echo "Converting to OGG..."

for key in "${!PHRASES[@]}"; do
  ffmpeg -y -i "wav/${key}.wav" \
    -filter:a loudnorm=I=-14:LRA=1:dual_mono=true:tp=-1 \
    -c:a libvorbis -ar 16000 -b:a 64k \
    "ogg/${key}.ogg" -loglevel error
done

echo "Packing..."
cd ogg
tar czf ../dreame-czech-vlasta.tar.gz *.ogg
cd ..

md5sum dreame-czech-vlasta.tar.gz
du -b dreame-czech-vlasta.tar.gz

echo "Done! Upload dreame-czech-vlasta.tar.gz to GitHub."
